import json
from pathlib import Path

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Context-Aware Brainrot Word-Level Detector Model Training Notebook\n",
        "\n",
        "This notebook trains a local binary classifier model (`distilbert-base-uncased`) to detect whether a specific word is used as **brainrot slang** (label 1) or **standard English** (label 0) in the context of a given sentence.\n",
        "\n",
        "### Input Format:\n",
        "Inputs are formatted as: `Word: {word} | Context: {sentence}`\n",
        "\n",
        "### Training Workflow:\n",
        "1. Extract positive context-aware examples by finding occurrences of slang terms (and their morphological variations like `yapping`, `rizzler`, `cooked`) in the training sentences of `translation_quality_classifier_dataset.csv` (label 1).\n",
        "2. Compile a negative set of standard English words for homonyms (like `cooked`, `tea`, `cap`, `bet`, `glaze`, `edge`, `slay`, `aura`, `mid`, `lit`) where they are used in their literal/non-slang sense (label 0).\n",
        "3. Extract normal English words from the clean candidate translations in the dataset and pair them with their sentences (label 0).\n",
        "4. Tokenize the context-paired dataset using the `distilbert-base-uncased` tokenizer.\n",
        "5. Train `distilbert-base-uncased` with a sequence classification head for 3 epochs using PyTorch.\n",
        "6. Evaluate model performance using Accuracy, Precision, Recall, and F1-score.\n",
        "7. Run context-aware smoke tests (e.g., distinguishing *\"I cooked steak\"* from *\"bro is cooked\"*) and export the trained model to a ZIP file.\n",
        "\n",
        "### Colab Instructions:\n",
        "- Run this notebook in Google Colab with a GPU runtime (Runtime > Change runtime type > T4 GPU).\n",
        "- Upload `slang_terms.csv` and `translation_quality_classifier_dataset.csv` when prompted, or place them in the same directory as this notebook."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Install required dependencies in Google Colab\n",
        "!pip -q install transformers datasets accelerate sentencepiece evaluate safetensors scikit-learn pandas tqdm torch"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import re\n",
        "import random\n",
        "from pathlib import Path\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import torch\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from tqdm.auto import tqdm\n",
        "from transformers import AutoModelForSequenceClassification, AutoTokenizer, get_linear_schedule_with_warmup\n",
        "from sklearn.metrics import accuracy_score, precision_recall_fscore_support\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "# Set random seeds for reproducibility\n",
        "SEED = 42\n",
        "random.seed(SEED)\n",
        "np.random.seed(SEED)\n",
        "torch.manual_seed(SEED)\n",
        "if torch.cuda.is_available():\n",
        "    torch.cuda.manual_seed_all(SEED)\n",
        "\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(\"Using device:\", device)\n",
        "if torch.cuda.is_available():\n",
        "    print(\"GPU Device Name:\", torch.cuda.get_device_name(0))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 1. Dataset Loading & Setup"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Support Google Colab file upload or local relative paths\n",
        "slang_path = Path(\"slang_terms.csv\")\n",
        "if not slang_path.exists() and Path(\"../data/processed/slang_terms.csv\").exists():\n",
        "    slang_path = Path(\"../data/processed/slang_terms.csv\")\n",
        "\n",
        "qual_path = Path(\"translation_quality_classifier_dataset.csv\")\n",
        "if not qual_path.exists() and Path(\"../data/processed/translation_quality_classifier_dataset.csv\").exists():\n",
        "    qual_path = Path(\"../data/processed/translation_quality_classifier_dataset.csv\")\n",
        "\n",
        "# Trigger upload if not found locally\n",
        "if not slang_path.exists() or not qual_path.exists():\n",
        "    try:\n",
        "        from google.colab import files\n",
        "        print(\"Please upload slang_terms.csv and translation_quality_classifier_dataset.csv:\")\n",
        "        uploaded = files.upload()\n",
        "        for fname in uploaded.keys():\n",
        "            if \"slang\" in fname:\n",
        "                slang_path = Path(fname)\n",
        "            elif \"classifier\" in fname or \"quality\" in fname:\n",
        "                qual_path = Path(fname)\n",
        "    except ImportError:\n",
        "        raise FileNotFoundError(\"Dataset files not found. Please place slang_terms.csv and translation_quality_classifier_dataset.csv in this directory.\")\n",
        "\n",
        "df_slang = pd.read_csv(slang_path)\n",
        "df_slang = df_slang.dropna(subset=[\"term\"])\n",
        "base_slang_terms = sorted(list(set(df_slang[\"term\"].astype(str).str.strip().str.lower())))\n",
        "\n",
        "df_qual = pd.read_csv(qual_path)\n",
        "df_qual = df_qual.dropna(subset=[\"source_text\", \"candidate_translation\"])\n",
        "\n",
        "print(f\"Loaded {len(base_slang_terms)} base slang terms.\")\n",
        "print(f\"Loaded {len(df_qual)} sentence translation evaluation pairs.\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2. Morphological Slang Augmentation & Positive Context Extraction"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def augment_word(word, is_slang=False):\n",
        "    word = word.strip().lower()\n",
        "    if not word or len(word) < 2:\n",
        "        return [word] if word else []\n",
        "        \n",
        "    variations = {word}\n",
        "    \n",
        "    # 1. Plurals\n",
        "    if word.endswith(('s', 'x', 'z', 'ch', 'sh')):\n",
        "        variations.add(word + \"es\")\n",
        "    else:\n",
        "        variations.add(word + \"s\")\n",
        "        \n",
        "    # 2. Gerunds (-ing)\n",
        "    if word.endswith('e') and not word.endswith('ee'):\n",
        "        variations.add(word[:-1] + \"ing\")\n",
        "    elif word[-1] in 'bdfgklmnprst' and word[-2] in 'aeiou' and (len(word) < 3 or word[-3] not in 'aeiou'):\n",
        "        variations.add(word + word[-1] + \"ing\")\n",
        "    else:\n",
        "        variations.add(word + \"ing\")\n",
        "        \n",
        "    # 3. Past tense (-ed)\n",
        "    if word.endswith('e'):\n",
        "        variations.add(word + \"d\")\n",
        "    elif word[-1] in 'bdfgklmnprst' and word[-2] in 'aeiou' and (len(word) < 3 or word[-3] not in 'aeiou'):\n",
        "        variations.add(word + word[-1] + \"ed\")\n",
        "    else:\n",
        "        variations.add(word + \"ed\")\n",
        "        \n",
        "    # 4. Agent nouns (-er / -ler)\n",
        "    if is_slang and word == \"rizz\":\n",
        "        variations.add(\"rizzler\")\n",
        "        variations.add(\"rizzlers\")\n",
        "    if word.endswith('e'):\n",
        "        variations.add(word + \"r\")\n",
        "    elif word[-1] in 'bdfgklmnprst' and word[-2] in 'aeiou' and (len(word) < 3 or word[-3] not in 'aeiou'):\n",
        "        variations.add(word + word[-1] + \"er\")\n",
        "    else:\n",
        "        variations.add(word + \"er\")\n",
        "        \n",
        "    return list(variations)\n",
        "\n",
        "def augment_term(term, is_slang=False):\n",
        "    term = term.strip().lower()\n",
        "    if not term:\n",
        "        return []\n",
        "    if \" \" in term:\n",
        "        return [term]\n",
        "    return augment_word(term, is_slang)\n",
        "\n",
        "# Build positive dataset from quality classifier sentences containing slang\n",
        "augmented_slang_set = set()\n",
        "for term in base_slang_terms:\n",
        "    augmented_slang_set.update(augment_term(term, is_slang=True))\n",
        "augmented_slang_set = sorted(list(augmented_slang_set))\n",
        "\n",
        "sentences = list(set(df_qual[\"source_text\"].astype(str).str.strip().tolist()))\n",
        "positive_context_examples = []\n",
        "\n",
        "for sentence in tqdm(sentences, desc=\"Extracting slang matches\"):\n",
        "    lower_sent = sentence.lower()\n",
        "    for slang_var in augmented_slang_set:\n",
        "        pattern = rf\"\\b{re.escape(slang_var)}\\b\"\n",
        "        if re.search(pattern, lower_sent):\n",
        "            positive_context_examples.append({\n",
        "                \"word\": slang_var,\n",
        "                \"context\": sentence,\n",
        "                \"label\": 1\n",
        "            })\n",
        "\n",
        "print(f\"Generated {len(positive_context_examples)} positive (slang-in-context) examples. Sample:\")\n",
        "if positive_context_examples:\n",
        "    print(random.sample(positive_context_examples, min(5, len(positive_context_examples))))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3. Negative Context-Aware Data Generation\n",
        "\n",
        "To prevent the model from assuming a word like `cooked` is always brainrot, we generate standard sentences where these homonym words are used in their standard, literal sense. We also extract standard words from the clean translation sentences and pair them with their standard contexts."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Standard sentences for common homonyms\n",
        "homonym_sentences = {\n",
        "    \"cooked\": [\n",
        "        \"She cooked a wonderful roast for dinner.\",\n",
        "        \"The food was cooked to perfection.\",\n",
        "        \"We cooked some fresh vegetables in the kitchen.\",\n",
        "        \"He has cooked professionally for ten years.\",\n",
        "        \"The chicken must be fully cooked before eating.\",\n",
        "        \"They cooked a meal together on the weekend.\",\n",
        "        \"She cooked lunch for the whole family.\"\n",
        "    ],\n",
        "    \"tea\": [\n",
        "        \"Would you like a hot cup of green tea?\",\n",
        "        \"She drinks black tea every morning.\",\n",
        "        \"The tea was imported from a famous plantation.\",\n",
        "        \"He brewed some herbal tea to relax.\",\n",
        "        \"Please pass the sugar for my tea.\",\n",
        "        \"Ice tea is very refreshing during the summer.\"\n",
        "    ],\n",
        "    \"basic\": [\n",
        "        \"We need to master the basic elements of science.\",\n",
        "        \"The chemistry class tested a basic solution.\",\n",
        "        \"This software tutorial covers the basic setup.\",\n",
        "        \"The hotel room was clean but very basic.\",\n",
        "        \"They taught us basic skills like reading maps.\",\n",
        "        \"His explanation was basic and easy to understand.\"\n",
        "    ],\n",
        "    \"cap\": [\n",
        "        \"He wore a red baseball cap to the game.\",\n",
        "        \"Please screw the cap back onto the bottle.\",\n",
        "        \"The budget has a strict spending cap.\",\n",
        "        \"The mountain peak was covered in a snow cap.\",\n",
        "        \"The dental crown is a custom protective cap.\",\n",
        "        \"She put a blue cap on her pen.\"\n",
        "    ],\n",
        "    \"bet\": [\n",
        "        \"I placed a small bet on the football match.\",\n",
        "        \"She lost her bet on the horse race.\",\n",
        "        \"It is a safe bet that the event will be postponed.\",\n",
        "        \"He bet ten dollars that he could win the game.\",\n",
        "        \"They made a friendly bet about the weather.\"\n",
        "    ],\n",
        "    \"glaze\": [\n",
        "        \"The potter applied a shiny blue glaze to the vase.\",\n",
        "        \"The baker will glaze the donuts with sugar syrup.\",\n",
        "        \"A thin layer of ice glaze covered the highway.\",\n",
        "        \"She watched him glaze the clay plates.\",\n",
        "        \"The window has a double glaze for insulation.\"\n",
        "    ],\n",
        "    \"edge\": [\n",
        "        \"Do not stand too close to the edge of the roof.\",\n",
        "        \"The kitchen knife has an extremely sharp edge.\",\n",
        "        \"The forest is located at the edge of the town.\",\n",
        "        \"She walked along the water's edge.\",\n",
        "        \"The garden border has a neat stone edge.\"\n",
        "    ],\n",
        "    \"slay\": [\n",
        "        \"The brave knight did slay the fire dragon.\",\n",
        "        \"The soldiers were ordered to slay the monsters.\",\n",
        "        \"Ancient legends speak of heroes who slay beasts.\"\n",
        "    ],\n",
        "    \"aura\": [\n",
        "        \"The peaceful forest had an aura of serenity.\",\n",
        "        \"She believed she could feel a positive aura.\",\n",
        "        \"The historic building possesses a mysterious aura.\",\n",
        "        \"His calm aura helped soothe the nervous patients.\"\n",
        "    ],\n",
        "    \"lit\": [\n",
        "        \"We lit a candle when the electricity failed.\",\n",
        "        \"The street lamp was lit at sunset.\",\n",
        "        \"A warm fire was lit in the fireplace.\"\n",
        "    ],\n",
        "    \"mid\": [\n",
        "        \"The mid section of the bridge is undergoing repairs.\",\n",
        "        \"They met in mid August for their vacation.\",\n",
        "        \"The temperature peaked in the mid seventies.\"\n",
        "    ],\n",
        "    \"bop\": [\n",
        "        \"The child gave the balloon a light bop.\",\n",
        "        \"He received a tiny bop on his head from the toy.\"\n",
        "    ],\n",
        "    \"dog\": [\n",
        "        \"The dog chased the cat across the backyard.\",\n",
        "        \"They took their dog for a walk in the park.\"\n",
        "    ],\n",
        "    \"goat\": [\n",
        "        \"The goat climbed up the rocky hill.\",\n",
        "        \"They bought goat milk from the local farm.\"\n",
        "    ]\n",
        "}\n",
        "\n",
        "negative_context_examples = []\n",
        "\n",
        "# 1. Add literal homonym examples\n",
        "for word, sents in homonym_sentences.items():\n",
        "    for sent in sents:\n",
        "        negative_context_examples.append({\n",
        "            \"word\": word,\n",
        "            \"context\": sent,\n",
        "            \"label\": 0\n",
        "        })\n",
        "\n",
        "# 2. Extract standard words from clean translations in translation quality dataset\n",
        "df_good_translations = df_qual[df_qual[\"label\"] == 1]\n",
        "augmented_slang_set_lookup = set(augmented_slang_set)\n",
        "\n",
        "for _, row in tqdm(df_good_translations.iterrows(), total=len(df_good_translations), desc=\"Extracting negative words\"):\n",
        "    translation = str(row[\"candidate_translation\"]).strip()\n",
        "    if not translation:\n",
        "        continue\n",
        "    \n",
        "    # Find all words that have length > 2\n",
        "    words = re.findall(r\"\\b[a-zA-Z]{3,}\\b\", translation)\n",
        "    if words:\n",
        "        # Extract up to 2 standard words from this sentence\n",
        "        sampled = random.sample(words, min(2, len(words)))\n",
        "        for word in sampled:\n",
        "            word_lower = word.lower()\n",
        "            # Ensure the selected word is not a slang variation\n",
        "            if word_lower not in augmented_slang_set_lookup:\n",
        "                negative_context_examples.append({\n",
        "                    \"word\": word_lower,\n",
        "                    \"context\": translation,\n",
        "                    \"label\": 0\n",
        "                })\n",
        "\n",
        "print(f\"Generated {len(negative_context_examples)} negative (standard-in-context) examples. Sample:\")\n",
        "if negative_context_examples:\n",
        "    print(random.sample(negative_context_examples, min(5, len(negative_context_examples))))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4. Dataset Combination & Splitting"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Convert list to DataFrame\n",
        "df_pos = pd.DataFrame(positive_context_examples)\n",
        "df_neg = pd.DataFrame(negative_context_examples)\n",
        "\n",
        "# Balance the dataset to avoid biases\n",
        "min_size = min(len(df_pos), len(df_neg))\n",
        "df_pos_balanced = df_pos.sample(n=min_size, random_state=SEED)\n",
        "df_neg_balanced = df_neg.sample(n=min_size, random_state=SEED)\n",
        "\n",
        "df_dataset = pd.concat([df_pos_balanced, df_neg_balanced], ignore_index=True)\n",
        "df_dataset = df_dataset.sample(frac=1, random_state=SEED).reset_index(drop=True)\n",
        "\n",
        "print(\"Balanced dataset size:\", len(df_dataset))\n",
        "print(\"Class balance check:\")\n",
        "print(df_dataset[\"label\"].value_counts())\n",
        "\n",
        "# Split into 85% Train / 15% Validation\n",
        "train_data, eval_data = train_test_split(\n",
        "    df_dataset,\n",
        "    test_size=0.15,\n",
        "    stratify=df_dataset[\"label\"].tolist(),\n",
        "    random_state=SEED\n",
        ")\n",
        "\n",
        "print(f\"Train size: {len(train_data)}, Validation size: {len(eval_data)}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 5. Tokenization & Dataset Loading"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "BASE_MODEL = \"distilbert-base-uncased\"\n",
        "MAX_LENGTH = 96 # Since we input 'Word: {word} | Context: {sentence}'\n",
        "\n",
        "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)\n",
        "\n",
        "class BrainrotContextDataset(Dataset):\n",
        "    def __init__(self, df_data):\n",
        "        self.words = df_data[\"word\"].tolist()\n",
        "        self.contexts = df_data[\"context\"].tolist()\n",
        "        self.labels = df_data[\"label\"].tolist()\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.words)\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        # Format input string\n",
        "        input_text = f\"Word: {self.words[idx]} | Context: {self.contexts[idx]}\"\n",
        "        return {\n",
        "            \"text\": input_text,\n",
        "            \"label\": self.labels[idx]\n",
        "        }\n",
        "\n",
        "def collate_fn(batch):\n",
        "    texts = [item[\"text\"] for item in batch]\n",
        "    labels = [item[\"label\"] for item in batch]\n",
        "    \n",
        "    encoded = tokenizer(\n",
        "        texts,\n",
        "        padding=True,\n",
        "        truncation=True,\n",
        "        max_length=MAX_LENGTH,\n",
        "        return_tensors=\"pt\"\n",
        "    )\n",
        "    encoded[\"labels\"] = torch.tensor(labels, dtype=torch.long)\n",
        "    return encoded\n",
        "\n",
        "BATCH_SIZE = 32\n",
        "train_dataset = BrainrotContextDataset(train_data)\n",
        "eval_dataset = BrainrotContextDataset(eval_data)\n",
        "\n",
        "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)\n",
        "eval_loader = DataLoader(eval_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 6. Model Definition & Training Loop"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "model = AutoModelForSequenceClassification.from_pretrained(\n",
        "    BASE_MODEL,\n",
        "    num_labels=2,\n",
        "    id2label={0: \"normal\", 1: \"brainrot\"},\n",
        "    label2id={\"normal\": 0, \"brainrot\": 1}\n",
        ")\n",
        "model.to(device)\n",
        "\n",
        "# Training Hyperparameters\n",
        "EPOCHS = 3\n",
        "LEARNING_RATE = 2e-5\n",
        "\n",
        "optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)\n",
        "total_steps = len(train_loader) * EPOCHS\n",
        "scheduler = get_linear_schedule_with_warmup(\n",
        "    optimizer,\n",
        "    num_warmup_steps=max(1, total_steps // 10),\n",
        "    num_training_steps=total_steps\n",
        ")\n",
        "\n",
        "def compute_metrics(eval_preds, eval_labels):\n",
        "    preds = np.argmax(eval_preds, axis=-1)\n",
        "    precision, recall, f1, _ = precision_recall_fscore_support(eval_labels, preds, average=\"binary\")\n",
        "    acc = accuracy_score(eval_labels, preds)\n",
        "    return {\n",
        "        \"accuracy\": acc,\n",
        "        \"precision\": precision,\n",
        "        \"recall\": recall,\n",
        "        \"f1\": f1\n",
        "    }\n",
        "\n",
        "def evaluate():\n",
        "    model.eval()\n",
        "    eval_preds = []\n",
        "    eval_true_labels = []\n",
        "    eval_loss = 0.0\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for batch in eval_loader:\n",
        "            inputs = {k: v.to(device) for k, v in batch.items()}\n",
        "            outputs = model(**inputs)\n",
        "            loss = outputs.loss\n",
        "            eval_loss += loss.item()\n",
        "            \n",
        "            logits = outputs.logits.detach().cpu().numpy()\n",
        "            eval_preds.append(logits)\n",
        "            eval_true_labels.extend(batch[\"labels\"].numpy())\n",
        "            \n",
        "    eval_preds = np.concatenate(eval_preds, axis=0)\n",
        "    metrics = compute_metrics(eval_preds, eval_true_labels)\n",
        "    metrics[\"loss\"] = eval_loss / len(eval_loader)\n",
        "    model.train()\n",
        "    return metrics"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"Starting context-aware training loop...\")\n",
        "training_history = []\n",
        "\n",
        "for epoch in range(1, EPOCHS + 1):\n",
        "    model.train()\n",
        "    total_train_loss = 0.0\n",
        "    progress = tqdm(train_loader, desc=f\"Epoch {epoch}/{EPOCHS}\")\n",
        "    \n",
        "    for step, batch in enumerate(progress, start=1):\n",
        "        inputs = {k: v.to(device) for k, v in batch.items()}\n",
        "        \n",
        "        optimizer.zero_grad()\n",
        "        outputs = model(**inputs)\n",
        "        loss = outputs.loss\n",
        "        \n",
        "        if not torch.isfinite(loss):\n",
        "            raise RuntimeError(f\"Loss went to infinite/NaN at epoch {epoch}, step {step}\")\n",
        "            \n",
        "        loss.backward()\n",
        "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
        "        optimizer.step()\n",
        "        scheduler.step()\n",
        "        \n",
        "        total_train_loss += loss.item()\n",
        "        if step % 25 == 0:\n",
        "            progress.set_postfix(loss=total_train_loss / step)\n",
        "            \n",
        "    train_loss_avg = total_train_loss / len(train_loader)\n",
        "    eval_metrics = evaluate()\n",
        "    eval_metrics[\"train_loss\"] = train_loss_avg\n",
        "    eval_metrics[\"epoch\"] = epoch\n",
        "    \n",
        "    training_history.append(eval_metrics)\n",
        "    print(\n",
        "        f\"\\n[Epoch {epoch}] Train Loss: {train_loss_avg:.4f} | \"\n",
        "        f\"Val Loss: {eval_metrics['loss']:.4f} | \"\n",
        "        f\"Accuracy: {eval_metrics['accuracy']:.4f} | \"\n",
        "        f\"Precision: {eval_metrics['precision']:.4f} | \"\n",
        "        f\"Recall: {eval_metrics['recall']:.4f} | \"\n",
        "        f\"F1 Score: {eval_metrics['f1']:.4f}\"\n",
        "    )"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 7. Model Inference & Smoke Tests"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def predict_word_context(word, sentence):\n",
        "    input_text = f\"Word: {word.strip().lower()} | Context: {sentence.strip()}\"\n",
        "    inputs = tokenizer(input_text, return_tensors=\"pt\", truncation=True, max_length=MAX_LENGTH).to(device)\n",
        "    model.eval()\n",
        "    with torch.no_grad():\n",
        "        logits = model(**inputs).logits\n",
        "        probabilities = torch.softmax(logits, dim=-1)[0]\n",
        "        predicted_class = torch.argmax(probabilities).item()\n",
        "        confidence = probabilities[predicted_class].item()\n",
        "    \n",
        "    label = \"brainrot\" if predicted_class == 1 else \"normal\"\n",
        "    return label, confidence\n",
        "\n",
        "smoke_tests = [\n",
        "    # Test cooked (ambiguous)\n",
        "    (\"cooked\", \"bro is absolutely cooked in the replies\"),\n",
        "    (\"cooked\", \"she cooked a delicious steak for dinner\"),\n",
        "    # Test tea (ambiguous)\n",
        "    (\"tea\", \"spill the tea about what happened at the party\"),\n",
        "    (\"tea\", \"I prefer to drink hot green tea in the morning\"),\n",
        "    # Test basic (ambiguous)\n",
        "    (\"basic\", \"she is so basic with her pumpkin spice latte\"),\n",
        "    (\"basic\", \"this chemistry class covers basic solutions\"),\n",
        "    # Test rizz (unambiguous slang)\n",
        "    (\"rizz\", \"he has a lot of rizz\"),\n",
        "    (\"rizzler\", \"watch out for the rizzler\"),\n",
        "    # Test standard words\n",
        "    (\"computer\", \"the developer opened the computer\"),\n",
        "    (\"running\", \"she was running in the park\")\n",
        "]\n",
        "\n",
        "print(\"Running context-aware smoke tests:\")\n",
        "print(\"-\" * 70)\n",
        "for word, sentence in smoke_tests:\n",
        "    label, confidence = predict_word_context(word, sentence)\n",
        "    print(f\"Word: {word:<10} | Context: {sentence:<50} => Predict: {label:<10} (Conf: {confidence:.4f})\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 8. Saving & Exporting Weights"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "from pathlib import Path\n",
        "\n",
        "OUTPUT_DIR = Path(\"brainrot-detector-v1\")\n",
        "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "# Save tokenizer and model weights\n",
        "model.save_pretrained(OUTPUT_DIR, safe_serialization=True)\n",
        "tokenizer.save_pretrained(OUTPUT_DIR)\n",
        "\n",
        "# Save evaluation metrics report\n",
        "report = {\n",
        "    \"base_model\": BASE_MODEL,\n",
        "    \"epochs\": EPOCHS,\n",
        "    \"learning_rate\": LEARNING_RATE,\n",
        "    \"final_train_loss\": training_history[-1][\"train_loss\"],\n",
        "    \"final_eval_metrics\": {\n",
        "        \"loss\": training_history[-1][\"loss\"],\n",
        "        \"accuracy\": training_history[-1][\"accuracy\"],\n",
        "        \"precision\": training_history[-1][\"precision\"],\n",
        "        \"recall\": training_history[-1][\"recall\"],\n",
        "        \"f1\": training_history[-1][\"f1\"]\n",
        "    },\n",
        "    \"history\": training_history\n",
        "}\n",
        "\n",
        "with open(OUTPUT_DIR / \"metrics_report.json\", \"w\", encoding=\"utf-8\") as f:\n",
        "    json.dump(report, f, indent=2)\n",
        "\n",
        "print(f\"Model and tokenizer weights saved to: {OUTPUT_DIR}\")\n",
        "\n",
        "# Compress files into ZIP archive for download in Google Colab\n",
        "!zip -qr brainrot-detector-v1.zip brainrot-detector-v1\n",
        "print(\"ZIP file packaged: brainrot-detector-v1.zip\")\n",
        "\n",
        "try:\n",
        "    from google.colab import files\n",
        "    files.download(\"brainrot-detector-v1.zip\")\n",
        "    print(\"Triggered automatic file download.\")\n",
        "except ImportError:\n",
        "    print(\"Local environment: ZIP file ready. Copy or extract brainrot-detector-v1 folder into project models.\")"
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

# Write output file
output_path = Path("notebooks/train_brainrot_detector.ipynb")
output_path.parent.mkdir(parents=True, exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Successfully generated notebook: {output_path}")
